# .github/workflows/docker.yml
name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login 
    run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

    - name: build 
    run: docker build -t noelanderos/api-monos:${{github.sha}} .

    - name: tag 
    run: docker tag noelanderos/api-monos:${{github.sha}} noelanderos/api-monos:latest

    - name: push
    run: |
      docker push noelanderos/api-monos:${{github.sha}}
      docker push noelanderos/api-monos:latest




    